import React from "react";
import { SuggestionChip } from "../../components/SuggestionChip";
import "./style.scss";

export const Box = (): JSX.Element => {
  return (
    <div className="box" data-model-id="422:12034-frame">
      <div className="div">
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="disabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="disabled"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="disabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="disabled"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="dragged"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="dragged"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="dragged"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="dragged"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="pressed"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="pressed"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="pressed"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="pressed"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="focused"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="focused"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="focused"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="focused"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="hovered"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="hovered"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="hovered"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="hovered"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="enabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon
          stateProp="enabled"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="enabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected
          showIcon={false}
          stateProp="enabled"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="disabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="disabled"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="disabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="disabled"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="dragged"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="dragged"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="dragged"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="dragged"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="pressed"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="pressed"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="pressed"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="pressed"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="focused"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="focused"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="focused"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="focused"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="hovered"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="hovered"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="hovered"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="hovered"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="enabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon
          stateProp="enabled"
          style="outlined"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="enabled"
          style="elevated"
        />
        <SuggestionChip
          className="suggestion-chip-instance"
          labelText="Label"
          selected={false}
          showIcon={false}
          stateProp="enabled"
          style="outlined"
        />
      </div>
    </div>
  );
};
